# Generated by Django 4.2.16 on 2024-10-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_patient_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
